### ISSUE TITLE
[Feature Request] Signals or Events on Shake completion

### ISSUE THREAD

**Issue by Loregret** [Hyrdaboo/DwarfImpulse#2]
Hi there! Great plugin!

I was searching the code of the plugin for signals or events to determine when shake is finished. It seems there is none.

Could you add a signal for completion of the shake?

**Comment by Hyrdaboo** [comment]
@Loregret Done! 
```CSharp
// second optional parameter for onComplete callback
shakeDirector.Shake(yourNoisePreset, OnCompleteCallback);
```

I've updated the explosion demo too you can check it out.

**Comment by Loregret** [comment]
@Hyrdaboo Fast as lightning! ⚡

Thanks!
